# Generated by Django 5.2.12 on 2026-04-14 00:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_avatar_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuddyRelationship",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "buddy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buddy_of",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buddies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_buddies",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "buddy"), name="unique_buddies"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("user", models.F("buddy")), _negated=True),
                        name="no_self_buddy",
                        violation_error_message="A user cannot add themselves as a buddy",
                    ),
                ],
            },
        ),
    ]
