# Generated by Django 6.0.3 on 2026-03-12 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_recommendations', to='users.user'),
        ),
        migrations.AddField(
            model_name='buddyrecommendation',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_buddy_recommendations', to='users.user'),
        ),
        migrations.AddField(
            model_name='buddyrecommendation',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_buddy_recommendations', to='users.user'),
        ),
        migrations.AddConstraint(
            model_name='bookrecommendation',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_book_recommendation'),
        ),
        migrations.AddConstraint(
            model_name='buddyrecommendation',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_buddy_recommendation'),
        ),
    ]
