# Generated by Django 6.0.3 on 2026-03-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='buddyrecommendation',
            constraint=models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='buddy_recommendation_no_self_recommendations', violation_error_message='A user cannot be recommended themselves as a buddy'),
        ),
    ]
