# Generated by Django 6.0.3 on 2026-03-12 19:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openlibrary_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('bio', models.TextField(blank=True, default='')),
                ('photo_url', models.URLField(blank=True, default='')),
            ],
            options={
                'db_table': 'books_author',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'books_book_review',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openlibrary_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('cover_url', models.URLField(blank=True, default='')),
                ('authors', models.ManyToManyField(blank=True, related_name='books', to='books.author')),
            ],
            options={
                'db_table': 'books_book',
            },
        ),
        migrations.CreateModel(
            name='ShelfEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('want_to_read', 'Want to Read'), ('currently_reading', 'Currently Reading'), ('read', 'Read'), ('did_not_finish', 'Did Not Finish')], default='want_to_read', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_entries', to='books.book')),
            ],
            options={
                'db_table': 'books_shelf_entry',
            },
        ),
    ]
