# Generated by Django 6.0.3 on 2026-03-12 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_entries', to='users.user'),
        ),
        migrations.AddField(
            model_name='review',
            name='shelf_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='books.shelfentry'),
        ),
        migrations.AddConstraint(
            model_name='shelfentry',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_shelf_entry'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='rating_between_1_and_5', violation_error_message='Rating must be between 1 and 5'),
        ),
    ]
